[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
authors = ["moghtech <contact@mogh.tech>"]
license = "MIT"
repository = "https://github.com/moghtech/lib"
# homepage = "https://mogh.tech/lib"
publish = ["mogh"]

[patch.mogh]
mogh_cache = { path = "crates/cache" }
mogh_config = { path = "crates/config" }
mogh_error = { path = "crates/error" }
mogh_logger = { path = "crates/logger" }
mogh_rate_limit = { path = "crates/rate_limit" }
mogh_secret_file = { path = "crates/secret_file" }

[workspace.dependencies]
# MOGH
mogh_cache = { version = "0.1.0", registry = "mogh" }
mogh_config = { version = "0.1.0", registry = "mogh" }
mogh_error = { version = "0.5.5", registry = "mogh" }
mogh_logger = { version = "0.1.0", registry = "mogh" }
mogh_rate_limit = { version = "0.1.0", registry = "mogh" }
mogh_secret_file = { version = "0.1.0", registry = "mogh" }

# ASYNC
tokio = { version = "1.49.0", features = ["full"] }

# SERVER
tower-http = { version = "0.6.8", features = ["fs", "cors", "set-header"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
axum = { version = "0.8.8", features = ["macros"] }
tower-sessions = "0.14.0"
url = "2.5.7"

# SER/DE
indexmap = { version = "2.12.1", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
serde_json = "1.0.148"
serde_qs = "0.15.0"
toml = "0.9.8"

# ERROR
anyhow = "1.0.100"
thiserror = "2.0.17"

# LOGGING
opentelemetry-otlp = { version = "0.31.0", features = ["tls-roots", "reqwest-rustls"] }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
tracing-subscriber = { version = "0.3.22", features = ["json"] }
opentelemetry-semantic-conventions = "0.31.0"
tracing-opentelemetry = "0.32.0"
opentelemetry = "0.31.0"
tracing = "0.1.44"

# MISC
typeshare = "1.0.5"
wildcard = "0.3.0"
colored = "3.0.0"
utoipa = "5.4.0"
regex = "1.12.2"