[workspace]
resolver = "2"
members = ["auth/client/rs", "auth/server", "crates/*"]

[workspace.package]
edition = "2024"
authors = ["moghtech <contact@mogh.tech>"]
license = "MIT"
repository = "https://github.com/moghtech/lib"
# homepage = "https://mogh.tech/lib"
publish = ["mogh"]

[patch.mogh]
mogh_auth_client = { path = "auth/client/rs" }
mogh_cache = { path = "crates/cache" }
mogh_config = { path = "crates/config" }
mogh_error = { path = "crates/error" }
mogh_logger = { path = "crates/logger" }
mogh_rate_limit = { path = "crates/rate_limit" }
mogh_request_ip = { path = "crates/request_ip" }
mogh_secret_file = { path = "crates/secret_file" }
mogh_server = { path = "crates/server" }
mogh_validations = { path = "crates/validations" }

[workspace.dependencies]
# MOGH
mogh_auth_client = { version = "0.1.0", registry = "mogh" }
mogh_cache = { version = "0.1.0", registry = "mogh" }
mogh_config = { version = "0.1.0", registry = "mogh" }
mogh_error = { version = "0.5.5", registry = "mogh" }
mogh_logger = { version = "0.1.0", registry = "mogh" }
mogh_rate_limit = { version = "0.1.0", registry = "mogh" }
mogh_request_ip = { version = "0.1.0", registry = "mogh" }
mogh_secret_file = { version = "0.1.0", registry = "mogh" }
mogh_server = { version = "0.1.0", registry = "mogh" }
mogh_validations = { version = "0.1.0", registry = "mogh" }
derive_empty_traits = "0.1.0"
derive_variants = "1.0.0"
resolver_api = "3.0.0"

# ASYNC
reqwest = { version = "0.13.1", default-features = false, features = ["json", "rustls"] }
tokio = { version = "1.49.0", features = ["full"] }

# SERVER
tower-http = { version = "0.6.8", features = ["fs", "cors", "set-header"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
axum = { version = "0.8.8", features = ["macros"] }
tower-sessions = "0.14.0"
url = "2.5.8"

# SER/DE
indexmap = { version = "2.12.1", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
serde_json = "1.0.149"
serde_qs = "0.15.0"
bson = "3.1.0"
toml = "0.9.8"

# AUTH
webauthn-rs = { version = "0.5.4", features = ["danger-allow-state-serialisation"] }
jsonwebtoken = { version = "10.2.0", features = ["aws_lc_rs"] }
totp-rs = { version = "5.7.0", features = ["qr", "serde_support"] }
data-encoding = "2.9.0"
bcrypt = "0.17.1"
rand = "0.9.2"

# ERROR
anyhow = "1.0.100"
thiserror = "2.0.17"

# LOGGING
opentelemetry-otlp = { version = "0.31.0", features = ["tls-roots", "reqwest-rustls"] }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
tracing-subscriber = { version = "0.3.22", features = ["json"] }
opentelemetry-semantic-conventions = "0.31.0"
tracing-opentelemetry = "0.32.0"
opentelemetry = "0.31.0"
tracing = "0.1.44"

# MISC
uuid = { version = "1.19.0", features = ["v4"] }
typeshare = "1.0.5"
wildcard = "0.3.0"
colored = "3.0.0"
utoipa = "5.4.0"
regex = "1.12.2"
