[package]
name = "mogh_request_ip"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# MOGH
mogh_error = { workspace = true, features = ["axum"] }
# EXTERNAL
anyhow.workspace = true
axum.workspace = true